// <auto-generated />
namespace ProjectQuanLyBanHang.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addHoVaTen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHoVaTen));
        
        string IMigrationMetadata.Id
        {
            get { return "202501150941000_addHoVaTen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
